### ISSUE TITLE
404

### ISSUE THREAD

**Issue by jersonal-com** [CSE-Software/Howto#1]
The link to template.tex on the page around Google Doc to LaTeX conversion:

https://cse-software.github.io/Howto/data/template.tex

produces a 404 error. Would be awesome if you could provide a link to this file.

**Comment by maherou** [comment]
I have placed a copy of template.tex in the expected location.  It has been some time since the proposed workflow has been exercised so some of the details may not be accurate but at least the file is there.  Thanks for bringing this to our attention.
